### ISSUE TITLE
Security headers are not added to the ingress file when adding a new site

### ISSUE THREAD

**Issue by rudivanhierden** [Amsterdam/openstad-management-panel#16]
**Description**
When adding a new site in the admin panel, the following security headers are not set:

- X-Content-Type-Options
- X-Frame-Options
- X-Xss-Protection
- Referrer-Policy

**Suggested fix**
These headers can be added to the ingress file through the configuration snippet:

```
nginx.ingress.kubernetes.io/configuration-snippet: | 
    more_set_headers "X-Content-Type-Options: nosniff";  
    more_set_headers "X-Frame-Options: SAMEORIGIN"; 
    more_set_headers "X-Xss-Protection: 1"; 
    more_set_headers "Referrer-Policy: same-origin";
```

Related ticket: https://trello.com/c/0z7gIphE/90-security-headers-toevoegen-aan-ingress-bij-aanmaken-van-een-nieuwe-site

**Comment by ToshKoevoets** [comment]
Resolved
